export const GET_CURRENT_HOUSEHOLD = 'GET_CURRENT_HOUSEHOLD';
export const NEW_HOUSEHOLD = 'NEW_HOUSEHOLD';
export const ADD_HOUSEHOLD = 'ADD_HOUSEHOLD';
export const EDIT_HOUSEHOLD = 'EDIT_HOUSEHOLD';
export const UPDATE_HOUSEHOLD = 'UPDATE_HOUSEHOLD';
export const DELETE_HOUSEHOLD = 'DELETE_HOUSEHOLD';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const EDIT_USER = 'EDIT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_CHORES = 'GET_CHORES';
export const NEW_CHORE = 'NEW_CHORE';
export const ADD_CHORE = 'ADD_CHORE';
export const EDIT_CHORE = 'EDIT_CHORE';
export const UPDATE_CHORE = 'UPDATE_CHORE';
export const DELETE_CHORE = 'DELETE_CHORE';
