# Generated by Django 4.0.2 on 2022-02-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0001_initial'),
        ('accounts', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chore.household'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
