# Generated by Django 4.0.2 on 2022-02-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0003_alter_user_household_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='doer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='chore.user'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
