# Generated by Django 4.0.2 on 2022-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0004_alter_chore_doer_alter_chore_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_digest',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
